[package]
name = "svarog-secp256k1"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
rug = { version = "1.28.1", features = ["serde"] }
serde = "1"

curve-abstract = { path = "../curve-abstract" }
secp256k1-sys = { path = "../secp256k1-sys" }
